### ISSUE TITLE
deprecated item ATOMIC_BOOL_INIT

### ISSUE THREAD

**Issue by m-mueller678** [phil-opp/rust-once#5]
the code generated by the macrro uses ATOMIC_BOOL_INIT, which has been deprecated in favor of const AtomicBool::new. This generates a warning for projects which use the macro.

if compatibility to older compiler versions is desired, #[allow(deprecated)] could be added instead of switching to AtomicBool::new.

**Comment by phil-opp** [comment]
Thanks for reporting! I opened #6 to fix this.
